### ISSUE TITLE
Продумать стратегию доставки

### ISSUE THREAD

**Issue by remnev** [remnev/4w#11]
Сделать подробный текст и положить на Диск

Прописать сроки доставки для каждого вида товара

У нас будет три типа: 
* доставка по Москве
* самовывоз из Москвы
* доставка Деловыми линиями

**Comment by saschahan** [comment]
На диске повесил расценки деловых линий. Как я и говорил, минималка 400-450 руб. Типа хабаровска 900 (отмечено желтым). В минималку (до 30 кг) входит около 5 рулонов. Здесь появилась мысль. Каждому рулону надо присвоить кг. И если клиент берет 7 рул, программа автоматом считает кг. Получается 35. И в графе доставка сразу должна увеличиваться стоимость. Задача: установить 30 кг минималка 450 руб, а далее каждый кг стоит 8 руб.

**Comment by remnev** [comment]
Как нам сейчас сделать попроще с киллограммами? Может пока не будем делать умный рассчет, а просто персонально с заказчиком по мылу/телефону общаться по поводу доп стоимости доставки?
