### ISSUE TITLE
Сделать форму параметров заказа

### ISSUE THREAD

**Issue by remnev** [remnev/4w#20]
Следующий шаг после добавления товара в заказ
* [x] не делать активную кнопку активной, пока все не заполнено
* [x] при выборе "другая дата" дать возможность ввести дату позже, чем предложенная ближайшая
* [x] оживить кнопку "Назад к списку товаров"
* [x] инициализировать блок при вызове, а не при загрузке страницы, чтобы учитывались только что добавленные товары
* [x] валидировать поля
* [x] добавить поле email

**Comment by remnev** [comment]
@saschahan Александр, вот так будет выглядеть форма:
![2015-05-08_1752](https://cloud.githubusercontent.com/assets/2083992/7538770/179d5b9a-f5ab-11e4-8a3c-de8719a71ed6.png)

Нормально?

Дата доставки если выпадает на выходные, то как мы поступаем? Доставляем в выходные? Склад работает в выходные?

**Comment by saschahan** [comment]
Все ок. В выходные склад не работает. Думаю, что касается профи, им и не надо. А с домохозяйками посмотрим. Там выходные будут важны. 


Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Yuriy <notifications@github.com> 
Дата:08.05.2015  17:54  (GMT+03:00) 
Кому: remnev/4w <4w@noreply.github.com> 
Копия: saschahan <saschahan@gmail.com> 
Тема: Re: [4w] Сделать форму параметров заказа (#20) 

@saschahan Александр, вот так будет выглядеть форма:


Нормально?

Дата доставки если выпадает на выходные, то как мы поступаем? Доставляем в выходные? Склад работает в выходные?

**Comment by remnev** [comment]
Выкатил эту форму. Можно проверить как она работает.
