### ISSUE TITLE
Подготовить список товаров для дома

### ISSUE THREAD

**Issue by remnev** [remnev/4w#6]
Разместить на Я Диске по аналогии с Профи

**Comment by saschahan** [comment]
очиститель для окооных рам (Edelweiss), смазка для уплотнения штапика, ручки с замками, заглушка паза штапика

**Comment by saschahan** [comment]
сетка от комаров (tesa)

**Comment by remnev** [comment]
Закиньте на диск в том же формате, что и профи.
